version: "3.8"
services:
  pytorch-jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    shm_size: '2g'
    ports:
      - 8888:8888 # for jupyter
      - 7860:7860 # for the gradio app
    command: jupyter notebook --ip 0.0.0.0 --no-browser --allow-root
    volumes:
      - ../:/workspace/notebooks
